[package]
name = "doorbell"
version = "0.1.0"
edition = "2021"

[dependencies]
rppal = "0.19"
paho-mqtt = { version = "0.12", features = ["vendored-ssl"] }
chrono = "0.4"
config = "0.14"
serde = { version = "1.0", features = ["derive"] }
